### ISSUE TITLE
RuntimeError :error building extension 'render_utils_cuda'

### ISSUE THREAD

**Issue by RuiYangQuan** [dvlab-research/BlockNeRFPytorch#11]
I'm running into this problem please ask when the cuda version is not compatible with the problem
![图片](https://user-images.githubusercontent.com/90050796/184613630-4fb49c6d-1bc1-46e5-b42b-a99d42b76941.png)
this is my configuration:
2080TI,cuda10.1,pytorch==1.7.0 torchvision==0.8.0  torchaudio==0.7.0  cudatoolkit=10.1 ( torch==1.7.1+cu101 torchvision==0.8.2+cu101 torchaudio==0.7.2)

**Comment by sjtuytc** [comment]
Please first refer to https://github.com/sunset1995/DirectVoxGO/issues/24 and https://github.com/sunset1995/DirectVoxGO/issues/24.

I guess the reason is that your CUDA version is too old so the cumsum_ function is not supported. If so, this problem cannot be easily addressed without updating your CUDA or re-writing the CUDA extension files.

**Comment by sjtuytc** [comment]
I close this issue temporally and please re-open this issue if the above solution does not address your problem.

**Comment by wt202020** [comment]
I change my gcc version from 5.4 to 7. it works.

**Comment by sjtuytc** [comment]
> I change my gcc vision from 5.4 to 7. it woks.

Thanks for your suggestions.
