### ISSUE TITLE
Could contributor update the latest NeRF information plz

### ISSUE THREAD

**Issue by Mr-ind1fferent** [dvlab-research/BlockNeRFPytorch#139]

**Comment by sjtuytc** [comment]
I recommend you to refer to [this link](https://github.com/MrNeRF/awesome-3D-gaussian-splatting#seminal-paper-introducing-3d-gaussian-splatting), where the contributor actively updates SOTA NeRF papers there.

Since the current NeRF domain is growing larger and larger and my research interests are changing, I feel sorry to say that I can't track NeRF literature in this repository.
