### ISSUE TITLE
A question about the transformation matrix for San Fran Cisco Mission Bay dataset 

### ISSUE THREAD

**Issue by mah-asd** [dvlab-research/BlockNeRFPytorch#140]
Hello, thanks for making this repository public, and providing the processed blocknerf dataset. I have a question about the transform matrix. I see the max and min value for y axis in the poses are around -5.45 and 5. However, in the blocknerf paper, they mentioned the data collection vehicle traveled 1.08 km. Is there any scale or the poses are relative poses with respect to the previous image?

**Comment by sjtuytc** [comment]
Thanks for your interest. I think they sample the data before making it public. I don't know the exact scale to convert the poses because the poses are acquired via COLMAP (according to their paper), and we usually only care about poses in the camera coordinate system (so I don't know much about the real values).
