### ISSUE TITLE
Is Block-NeRF amenable to instant-ngp optimizations?

### ISSUE THREAD

**Issue by corbt** [dvlab-research/BlockNeRFPytorch#23]
Nvidia has published [instant-ngp](https://github.com/NVlabs/instant-ngp), a refinement of the NeRF algorithm that allows for training times 2-3 orders of magnitude faster than traditional NeRFs.

Could Block-NeRF be adapted to use the same optimizations? My iteration speed would be much faster if it didn't take hours-days every time I wanted to experiment with a new set of collections! 😃

**Comment by sjtuytc** [comment]
Hi, I'm currently studying instant-ngp as well because currently, we have to rely on some tools from instant-ngp to create interactive scenes. As for development, incorporating instant-ngp is not very easy because it is dependent on CUDA and requires building every time. Besides, it needs a desktop version of GPU but we typically only have headless servers.

**Comment by corbt** [comment]
> Besides, it needs a desktop version of GPU but we typically only have headless servers.

FYI, I've successfully run renders headlessly as described [in the FAQ](https://github.com/NVlabs/instant-ngp#frequently-asked-questions-faq).

> it is dependent on CUDA and requires building every time

This is fair. There's a [pytorch port](https://github.com/ashawkey/torch-ngp) I've got running that doesn't require any compilation but the resulting NeRFs end up with more artifacts than when I run the same collections through instant-ngp. It certainly converges fast though! 😃

**Comment by sjtuytc** [comment]
Thanks for your suggestions! I will definitely look into it and catch up with these awesome techniques!

**Comment by ElliotQi** [comment]
How is it going? I'm also interested in the Block-Nerf with instant-ngp.
