### ISSUE TITLE
The custom data training effect is poor

### ISSUE THREAD

**Issue by lishulincug** [dvlab-research/BlockNeRFPytorch#47]
Run with their own data, the effect is poor, can't see 3 d effect, very fuzzy。

https://user-images.githubusercontent.com/13003282/203454463-57098029-f8a0-43db-80e1-12449d1dcab4.mp4
![image](https://user-images.githubusercontent.com/13003282/203455507-b59277eb-068a-4b35-b9dd-dfafd0a6de1b.png)
![image](https://user-images.githubusercontent.com/13003282/203455551-5a71e70f-fe55-4a64-89da-74cd64c029e6.png)

**Comment by sjtuytc** [comment]
Running on custom data is out of the scope of this repo because the custom cases can vary greatly and we cannot offer a solution to every case. However, I'd like to offer you some suggestions on your case:
1. Make sure that your poses are correct. In fact, I don't think COLMAP can trivially work well in your scenarios. You often need to tune COLMAP or use other SLAM tools to get the poses.
2. Visualize your cameras to make sure they are in the right geometry positions.
3. Currently you cannot see anything basically. If you make sure that the poses and the camera geometry is correct, you then need to set the scene box to the right positions.
4. Tune the NERF parameters to make everything right. This part is more tricky and you often need some engineering experience to get this perfectly. I cannot offer you much suggestions on this.

**Comment by sjtuytc** [comment]
Closed because of no response.

**Comment by rockywind** [comment]
Hi，
@lishulincug 
我训练自己的数据的测试结果也是很差。请问您是怎么解决的？
https://user-images.githubusercontent.com/14838781/206227152-d05c18f1-99d6-4c37-86f8-eaeeea2e5bc8.mp4

**Comment by lishulincug** [comment]
> Hi， @lishulincug 我训练自己的数据的测试结果也是很差。请问您是怎么解决的？ https://user-images.githubusercontent.com/14838781/206227152-d05c18f1-99d6-4c37-86f8-eaeeea2e5bc8.mp4

重新跑了遍数据还是那样，用colmap对数据进行三维场景又是可以生成三维场景的，也不知道是位姿数据不够准确造成的？没有解决。

**Comment by sjtuytc** [comment]
这个是floating问题，可以参考一些论文，我们也在持续研究
