### ISSUE TITLE
About Waymo's pose

### ISSUE THREAD

**Issue by JonasW-byte** [dvlab-research/BlockNeRFPytorch#53]
After visualize the waymo's training pose, here we can see, y axis is the car driving direction. If  in my dataset  z axis is the car driving direction, do I need transform the pose same as waymo training pose?

![image](https://user-images.githubusercontent.com/33064930/213344759-07a0761b-f9b8-45e9-8076-fdfb1700ba17.png)

**Comment by sjtuytc** [comment]
Thanks for your attention. If you are an expert on NeRF, you only need to keep the following setups consistent:
(1) Loading the camera poses.
(2) Parse the poses to rays.
(3) Set render poses.
But in my point of view, the car should run in the xy plane because normally z-axis is pointing to the sky. This is only a convention.

**Comment by JonasW-byte** [comment]
Thanks a lot. You are right, the car actually drives in x axis direction. But the transformed training dataset is in y axis. Anyway, we need keep the pose and ray consistent.
