### ISSUE TITLE
misleading contents

### ISSUE THREAD

**Issue by AIBluefisher** [dvlab-research/BlockNeRFPytorch#54]
I think the major part of this project is only a copy of Mega-NeRF. While in the code and README, this repo uses `BlockNeRF` and claims it supports BlockNeRF, which is actually not true and can be misleading to others. I think this issue should be fixed.

**Comment by sjtuytc** [comment]
Thanks for your attention and suggestions.
1. The Mega-NeRF has been removed. I'm busy with the next major release, so the docs seem to be inconsistent temporally. I don't think our repo will be related to Mega-NeRF in the future (because the setup and backbones are quite different). 
2. As for the improved Block-NeRF, it is explained in #45 . I have tried my best to make it online and I have been working on it for months. If you have a quicker or more accurate implementation, you can start and contribute to a new GitHub repo or create a PR to this repo.
