### ISSUE TITLE
academic discussion

### ISSUE THREAD

**Issue by JonasW-byte** [dvlab-research/BlockNeRFPytorch#56]
About NeRF generalization, as I have tested, if I use block_0 model to inference block_8 dataset, it's hard to get worthy result. So, the nerf model generalization is really like all kinds of references expressed that nerf's generalization is very poor? If we expand the block area, that means to train more data, e.g. treat one city dataset  as one block, then the generalization is better or not?

**Comment by JonasW-byte** [comment]
For example, we split the San Francisco dataset as training dataset and test dataset, and train the training dataset as one block, can we get better result on test dataset?

**Comment by sjtuytc** [comment]
This is a good question. In fact, the generalization of NeRF is a hard topic from my point of view. In the real world, two different places may have different physical properties (reflexity, density, etc). However, the physical laws (including the rendering law, Newton's laws, etc) keep constant when going from one place to another. We cannot guarantee that we can generalize the NeRF **from one place to another**. However, when testing NeRF performances, we can still sample from the local block so that we can generalize **from training views to unseen views**.

**Comment by sjtuytc** [comment]
Closed because of no further comment.

**Comment by JonasW-byte** [comment]
Yes, exactly. Except reflection, density, a lots of factors have influence on the generalization of NeRF. Movable object(vehicles, pedestrians, etc.) is also one of factors? because the collected sensors take photos at one place with different time in my dataset, which causes same place with different feature(color). sometime with movable object, sometimes not. If we remove the  object like waymo, that is a expensive engineer.
Btw, 2D rendering head maybe easier than depth output head? Because sometime we want to get reconstruct 3D scene from depth info. It's hard to keep consistent on same object and get better result on whole image.

**Comment by sjtuytc** [comment]
Yes, you are absolutely correct.
