### ISSUE TITLE
About big scane

### ISSUE THREAD

**Issue by szgy66** [dvlab-research/BlockNeRFPytorch#77]
Hi, I can run the example of your project very well. I want to extend your project to my own scenario, I wandered around the larger scene of the office making videos. Follow your guide to get the relevant groundtruth files and then run the project. But I got bad results. So I have two questions:
1. The project provides examples of the data set that are only forward-facing or 360 degrees, without relevant big scenes, so whether the project does not support big scenes.
2. If large scenarios can be supported, do my relevant config files need to be changed.
Thanks！Looking forward to your reply.

**Comment by sjtuytc** [comment]
Thanks for your attention and appreciation of our work.
Training large-scale NeRF is not easy, and many challenges are involved. Also, setting good hyperparameters is very important and challenging.
In the short term, I will make some tutorials (blogs or videos) on making our model work in a new large-scale scene. I hope that will help the community.
For now, you have to explore a bit by yourself because I am unsure whether your data quality is good (poses, image coverage, dynamic objects, etc).

**Comment by sjtuytc** [comment]
Closed because of no further comments.
