### ISSUE TITLE
question about FourierGrid

### ISSUE THREAD

**Issue by chufall** [dvlab-research/BlockNeRFPytorch#81]
Hi, Thank you for your great works!

I  have some confusion about FourierGrid。
Are there any papers or reports about this model?  From the code , I cannot get the structure of it very clearly.
Which the different betweem FourierGrid and block-nerf? 

Thanks   a lot!
qc

**Comment by sjtuytc** [comment]
Thanks for your attention and appreciation; it means a lot to us. You raised a very good question.
The paper has not been published, and we are still in progress and improving our paper.
As for the Block-NeRF, we cannot claim that we outperform the full version of Block-NeRF because 
(1) We fail to implement all working parts of Block-NeRF. For example, pose refinement and dynamic object removal require a lot of effort. We did not make it work after several months' of attempts. 
(2) The original Block-NeRF requires a lot of computational resources, which we do not have.
However, we implement some core elements of Block-NeRF: separately modeling different blocks and composing renderings together. And all the comparisons are conducted under this setting. So the relation between FourierGrid and BlockNeRF is: FourierGrid inherits some, but not all, techniques of BlockNeRF in modeling large-scale scenes.

**Comment by chufall** [comment]
I get it!  I look forward to see your paper!

**Comment by chufall** [comment]
I have a question about the block-nerf which metions in the Table 2
![image](https://user-images.githubusercontent.com/2565013/224216018-3524cb2e-1a7e-4689-b489-d0c0ae2441f9.png)
what's the meaning of the "weights" and "Total"?   

thanks a lot.

**Comment by sjtuytc** [comment]
We are not the authors of Block-NeRF, so we cannot give official explanations to you.
Here I think the meaning is Single-Block Weight / Total Block Weight.
Note 0.25M * 16 = 4.00M.

**Comment by sjtuytc** [comment]
Closed because of no further comments.
