### ISSUE TITLE
Do you support real-time rendering of grid-based NeRF?

### ISSUE THREAD

**Issue by synsin0** [dvlab-research/BlockNeRFPytorch#84]
In the FourierGrid implementation I have seen very fast convergence of NeRF variants, DGVO, Plenoxel. But I am conscious why the rendering speed is not as fast as training speed (e.g. 20mins for Waymo). Do you consider supporting more real-time rendering techniques?

**Comment by sjtuytc** [comment]
Thanks for your attention. Speeding up rendering is very interesting But We will not look into it in the short term. The major goal of this repo is to produce better renderings of unbounded scenes with minimum research effort. That means, We are not building complex coding systems with heavily optimized APIs. We are targeting research projects instead of industrial development. Speeding up rendering is beyond my bandit now.

**Comment by synsin0** [comment]
Thanks for your respond. I may look for other real-time nerf algorithms later. I have no more questions.
